### PR TITLE
docs(dcf-sandbox): Added DCF sandbox APP setup to the cheat sheet

### PR DESCRIPTION
**Pull request by vzpgb**

### CODE REVIEW

**Comment by paulineribeyre** [comment]
it's missing a couple others (see https://github.com/uc-cdis/data-portal/tree/master/data/config) but i actually don't know if we want this to be exhaustive 🤷‍♀️

**Comment by paulineribeyre** [comment]
maybe we could just replace the list with "available configs: link to portal repo"

**Comment by vzpgb** [comment]
3 left unmentioned: anvil, ibdgc, kfDcfInterop. Do you think we need to include them?

I needed APP value for DCF sandbox today, looked here and tried `dcf` which didn't work, because correct is `ncrdc-demo`, so I think we should keep it.

**Comment by vzpgb** [comment]
> with

Also good idea.

**Comment by vzpgb** [comment]
> maybe we could just replace the list with "available configs: link to portal repo"

Also good idea.

**Comment by vzpgb** [comment]
Changes were introduced in [this commit](https://github.com/uc-cdis/compose-services/compare/feat/dumpsh#diff-deefd60a0610774a8b100100002d04c9).

**Pull request closed without merging**
